insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "How many hours a week do you spend with your family?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b,question_type c where a.name='Family' and b.name='Approved' and c.name='Quantitative';
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "How many times a month do you argue with your parents?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b,question_type c where a.name='Family' and b.name='Approved' and c.name='Quantitative';
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "How many times a month do you argue with your siblings?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b,question_type c where a.name='Family' and b.name='Approved' and c.name='Quantitative';
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "How many times a month do you argue with your kids? (+have children)",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b,question_type c where a.name='Family' and b.name='Approved' and c.name='Quantitative';
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "How many siblings do you have?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b,question_type c where a.name='Family' and b.name='Approved' and c.name='Quantitative';
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "How many cousins do you have?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b,question_type c where a.name='Family' and b.name='Approved' and c.name='Quantitative';
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "How old was your mom when she had you?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b,question_type c where a.name='Family' and b.name='Approved' and c.name='Quantitative';
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "How old was your dad when he had you?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b,question_type c where a.name='Family' and b.name='Approved' and c.name='Quantitative';
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "What’s the right age to move out of your parents’ home?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b,question_type c where a.name='Family' and b.name='Approved' and c.name='Quantitative';
