update question set content="Do you think it\\'s your parent\\'s job to put you through college?" where question_id=21;
update question set content="Were you raised by parental figures who weren\\'t your biological parents?" where question_id=24;
update question set content="Do you think it\\’s okay for your parents to talk to you about sex?" where question_id=29;
update question set content="What\\'s more important to you, friends or family?" where question_id=39;
update question set content="Do you think it\\'s important to earn your in laws approval?" where question_id=43;
update question set content="If you are a part of a stepfamily, what\\'s it like?" where question_id=53;
update question set content="If you are adopted, how does it feel knowing you\\'re adopted?" where question_id=54;
update question set content="Is there something about your siblings that you\\'re specifically jealous of?" where question_id=57;
update question set content="How do you know if you\\'re ready for marriage? " where question_id=83;
update question set content="How do you know if you\\'re ready to have children?" where question_id=84;
update question set content="What is the worst experience you\\'ve ever had at home?" where question_id=86;
update question set content="Do you feel that you\\'re gay?" where question_id=95;
update question set content="Is there a secret you\\'re keeping from your family that you\\'re afraid to tell them?" where question_id=97;
update question set content="What are ways you try to earn your family\\'s respect?" where question_id=102;
update question set content="What are things about your family that you\\'re thankful for?" where question_id=105;
update question set content="What are things about your childhood that you\\'re thankful for?" where question_id=106;
update question set content="What\\'s the right age to move out of your parents\\' home?" where question_id=120;
update question set content="Do you think it\\'s important to eat breakfast?" where question_id=136;
update question set content="Tequila love or hate?" where question_id=173;
update question set content="Are there any foods that you wouldn\\'t eat as a child that you eat now?" where question_id=175;
update question set content="What do you think of people who say they\\'re not into food?" where question_id=195;
update question set content="Name your top 5 favorite restaurants and what\\'s good to order there." where question_id=197;
update question set content="Is there a food that you\\'ve had a bad experience with and will never eat again?" where question_id=210;
update question set content="What would you consider is American cuisine?" where question_id=221;
update question set content="What kind of foods do you like to eat when you\\'re stressed?" where question_id=224;
update question set content="Which do you prefer: rice, pasta, bread or potatoes?" where question_id=234;
update question set content="What are your tips for people who don\\'t know how to cook to get started?" where question_id=239;
update question set content="What\\'s your favorite spicy dish?" where question_id=241;
update question set content="What is the most unhealthy thing you\\'ve eaten today?" where question_id=264;
update question set content="What\\'s the best restaurant you\\'ve ever been to and why did you like it?" where question_id=267;
update question set content="What\\'s the absolute best way to prepare steak?" where question_id=268;
update question set content="What\\'s the absolute best way to prepare fish?" where question_id=269;
update question set content="What\\'s the absolute best way to prepare chicken?" where question_id=270;
update question set content="What\\'s the tastiest way to prepare vegetables that even someone who hates veggies will eat it?" where question_id=271;
update question set content="What\\'s the absolute best way to prepare seafood?" where question_id=272;
update question set content="What is the best food truck you\\'ve ever tried?" where question_id=277;
update question set content="How much does a restaurant\\'s health rating affect whether you eat there?" where question_id=278;
update question set content="What\\'s the best way to treat a burn in the kitchen?" where question_id=281;
update question set content="How many seconds can food be on the floor before you won\\'t eat it?" where question_id=286;
update question set content="How many days can you leave takeout in the fridge before it\\'s not okay to eat?" where question_id=287;
update question set content="How much was the most expensive meal you\\'ve ever had?" where question_id=290;
update question set content="What\\'s your best tip for people who are having a hard time committing to a fitness routine?" where question_id=370;
update question set content="What are some good workout options if you can\\'t afford a personal trainer?" where question_id=371;
update question set content="What is the best way to work out if I don\\'t have a gym membership?" where question_id=386;
update question set content="What\\'s the heaviest weight you\\'ve ever been? (lbs)" where question_id=408;
update question set content="What\\'s the lowest you\\'ve ever weighed? (lbs)" where question_id=409;
update question set content="What\\'s the longest distance you\\'ve ever run? (miles)" where question_id=411;
update question set content="What\\'s the longest distance you\\'ve ever biked? (miles)" where question_id=412;
update question set content="What\\'s the longest distance you\\'ve ever swam?" where question_id=413;
update question set content="What\\'s the longest distance (in miles) you\\'ve ever run?" where question_id=421;
update question set content="What\\'s the longest distance (in miles) you\\'ve ever biked?" where question_id=422;
update question set content="When you travel, which is more important: luxury or culture?" where question_id=430;
update question set content="What was the most unique vacation you\\'ve ever been on?" where question_id=458;
update question set content="What is the nicest hotel you\\'ve ever stayed at?" where question_id=460;
update question set content="What is the most spiritual experience you\\'ve had while traveling?" where question_id=476;
update question set content="What is the scariest experience you\\'ve ever had traveling alone?" where question_id=477;
update question set content="What is the most memorable experience you\\'ve ever had traveling alone?" where question_id=478;
update question set content="What vacation destinations would you recommend if you\\'re single?" where question_id=487;
update question set content="What vacation destinations are good places to party if you\\'re single?" where question_id=488;
update question set content="What is the most beautiful place you\\'ve ever visited?" where question_id=500;
update question set content="What\\'s your go to spot for a weekend getaway?" where question_id=506;
update question set content="What\\'s the best age to start taking a baby on a plane?" where question_id=513;
update question set content="If you saw your best friend\\'s partner kissing someone else, would you tell them?" where question_id=528;
update question set content="Do you believe we\\'ll discover extraterrestrial life in our lifetime? " where question_id=552;
update question set content="If you were at a restaurant and you didn\\'t like your order, would you ask for your money back?" where question_id=570;
update question set content="Like in \\'Eternal Sunshine of the Spotless Mind,\\' is there a relationship that you would want to erase?" where question_id=581;
update question set content="What\\'s the best way to cheer up someone who is down?" where question_id=607;
update question set content="How many dates does it take before you know it\\'s just not going to work with someone?" where question_id=631;
update question set content="What does \\'family\\' mean to you?" where question_id=717;
update question set content="What does \\'integrity\\' mean to you?" where question_id=718;
update question set content="What does \\'honor\\' mean to you?" where question_id=719;
update question set content="What does \\'cowardice\\' mean to you?" where question_id=720;
update question set content="How do you deal with it when you\\'re feeling jealous?" where question_id=732;
update question set content="What can you do today that you couldn\\'t do a year ago?" where question_id=750;
update question set content="What will you be able to do a year from now that you can\\'t or aren\\'t doing today?" where question_id=751;
update question set content="What do you think people\\'s first impression of you are?" where question_id=757;
update question set content="What do you have that you can\\'t live without?" where question_id=758;
update question set content="What\\'s stopping you from having the life that you want?" where question_id=773;
update question set content="What were your new year\\'s resolutions?" where question_id=779;
update question set content="Do you find that you are dating the same \\'type\\' over and over again?" where question_id=794;
update question set content="Who should do the asking out guys or girls?" where question_id=799;
update question set content="Do you believe that if a relationship isn\\'t work out, divorce is an option?" where question_id=802;
update question set content="Is someone\\'s past important to a relationship?" where question_id=818;
update question set content="How important is it that you get along with your partner\\'s parents?" where question_id=828;
update question set content="What\\'s more important: physical attraction or mental compatibility?" where question_id=834;
update question set content="Is it possible to change your partner\\'s bad habits?" where question_id=841;
update question set content="Have you ever dated someone you weren\\'t initially attracted to but then became attracted to?" where question_id=843;
update question set content="What\\'s more important: financial security or love?" where question_id=852;
update question set content="What\\'s better: being friends with someone first then developing feelings, or dating?" where question_id=858;
update question set content="What are 3 of your partner\\'s best traits?" where question_id=860;
update question set content="What are 3 of your partner\\'s worst traits?" where question_id=861;
update question set content="When you\\'ve gotten in a fight, how do you usually resolve it?" where question_id=876;
update question set content="What are things you wish your partner would do that they currently don\\'t do?" where question_id=877;
update question set content="Describe the best date you\\'ve ever been on and why." where question_id=881;
update question set content="What topics do you avoid talking about because you\\'re afraid of your partner\\'s reaction?" where question_id=885;
update question set content="When you\\'ve gotten in a fight, how do you usually resolve it?" where question_id=887;
update question set content="What are things you wish your partner would do that they currently don\\'t do?" where question_id=888;
update question set content="Describe the best date you\\'ve ever been on and why." where question_id=892;
update question set content="Describe someone you\\'ve met who fits your idea of a perfect mate." where question_id=896;
update question set content="What\\'s the best way to bring up wanting to try something kinky with your partner?" where question_id=913;
update question set content="What\\'s the best piece of advice you\\'ve ever gotten about relationships?" where question_id=917;
update question set content="What is your \\'go to\\' first date?" where question_id=924;
update question set content="What is the best way to show you\\'re interested in someone?" where question_id=926;
update question set content="What is the best way to let someone who is interested know you aren\\'t interested?" where question_id=927;
update question set content="What is the biggest secret you have kept from someone you\\'re in a relationship with?" where question_id=940;
update question set content="What is the most outrageous thing you\\'ve ever experienced on a date?" where question_id=953;
update question set content="What do you think about \\'saving it for marriage\\'?" where question_id=967;
update question set content="What are lies you can\\'t forgive in a relationship?" where question_id=979;
update question set content="What are the most common things you\\'ve argued about in relationships (past and present)?" where question_id=992;
update question set content="Could you be with someone who didn\\'t share your interests?" where question_id=994;
update question set content="If you are interested in someone who doesn\\'t know, what would it take for you to tell them?" where question_id=1000;
update question set content="How have your parents\\' marriage affected your view on relationships and marriage?" where question_id=1004;
update question set content="Do you think you\\'re ready for a serious relationship? Why or why not?" where question_id=1010;
update question set content="If your partner went out with for a boys\\'s night out/girls\\' night out, and you saw a video of the entire evening, do you think there would be something on it that would make you mad?" where question_id=1028;
update question set content="Is sex better when you\\'re with someone you\\'ve been with for a while?" where question_id=1036;
update question set content="When you\\'re sleeping with someone new, is it hard for you to cum?" where question_id=1044;
update question set content="Do you prefer sex when you\\'re drunk or high?" where question_id=1048;
update question set content="Do you prefer your partner shaved, trimmed or natural \\'down there?\\' " where question_id=1056;
update question set content="What is the kinkiest thing you\\'ve ever done?" where question_id=1097;
update question set content="What is the most adventurous place you\\'ve had sex?" where question_id=1101;
update question set content="Have you ever had a sexual encounter that you can\\'t tell anyone about?" where question_id=1103;
update question set content="Describe a sexual fantasy you have that you haven\\'t told your partner about." where question_id=1107;
update question set content="Describe a fantasy you\\'ve had about a teacher or superior." where question_id=1108;
update question set content="What\\'s the most embarrassing time you got caught masturbating?" where question_id=1114;
update question set content="What is your favorite fantasy when you\\'re masturbating?" where question_id=1115;
update question set content="Do you ever have thoughts other than your partner when you\\'re having sex?" where question_id=1122;
update question set content="How do you handle it if you\\'re with someone and can\\'t get an erection?" where question_id=1124;
update question set content="How do you handle it if you\\'re having sex and you lose your erection?" where question_id=1125;
update question set content="How do you feel when the guy you\\'re with can\\'t get hard?" where question_id=1126;
update question set content="How do you feel when the guy you\\'re with loses his erection in the middle of sex?" where question_id=1127;
update question set content="How do you handle it if a guy you\\'re with can\\'t get an erection?" where question_id=1128;
update question set content="What is the worst one night stand you\\'ve ever had?" where question_id=1135;
update question set content="What is the best one night stand you\\'ve ever had?" where question_id=1136;
update question set content="Why don\\'t men cum sometimes when having sex?" where question_id=1143;
update question set content="What is the most taboo thing you\\'ve ever done in bed?" where question_id=1144;
update question set content="What is something that you\\'ve wanted to do in bed that made a partner uncomfortable?" where question_id=1147;
update question set content="What thoughts turn you on when you\\'re having sex?" where question_id=1157;
update question set content="What\\'s the biggest age difference between you and someone you\\'ve slept with?" where question_id=1163;
update question set content="What\\'s the youngest a person should be to have sex?" where question_id=1164;
update question set content="What\\'s the most number of times you\\'ve had sex in a day?" where question_id=1165;
update question set content="What\\'s the most number of sex partners you\\'ve had in a day?" where question_id=1168;
update question set content="What\\'s the most number of sex partners you\\'ve had in a week?" where question_id=1169;
update question set content="What\\'s the most number of sex partners you\\'ve had in a year?" where question_id=1170;
update question set content="What\\'s the most number of sex partners you\\'ve had at the same time?" where question_id=1171;
update question set content="What\\'s the most number of times you\\'ve cum in a single session?" where question_id=1173;
update question set content="What\\'s the most number of times you\\'ve masturbated in a single day?" where question_id=1174;
update question set content="How old was the youngest person you\\'ve had sex with?" where question_id=1175;
update question set content="How old was the oldest person you\\'ve had sex with?" where question_id=1176;
update question set content="Do you think it\\'s a problem for couples in a relationship to work at the same office together?" where question_id=1190;
update question set content="Would you take a job that paid you more but was something you didn\\'t want to do as a profession?" where question_id=1197;
update question set content="Would it be hard to work with someone you\\'re in a relationship with?" where question_id=1202;
update question set content="If you noticed an extra direct deposit from your company that shouldn\\'t be there, would you bring it up?" where question_id=1204;
update question set content="Does a company\\'s cultural diversity (or lack of) affect your decision to take a job?" where question_id=1209;
update question set content="Do you think you\\'re getting paid more than you really should be?" where question_id=1217;
update question set content="How important to you is a company\\'s name when looking for a job?" where question_id=1222;
update question set content="What can\\'t you stand about your boss?" where question_id=1243;
update question set content="How would you deal with a situation in which you couldn\\'t meet a deadline at work?" where question_id=1255;
update question set content="Have you ever been \\'caught\\' having sex at work?" where question_id=1269;
update question set content="If you don\\'t like your job, why would you stay?" where question_id=1278;
update question set content="Does what you studied in college correspond to your what you\\'re doing now?" where question_id=1280;
update question set content="Have you ever had sex with someone whose name you didn\\’t know?" where question_id=1078;
