insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If a friend had bad breath, would you tell them?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If the bank teller accidentally credited you for $200 extra, would you say anything?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you believe people have souls?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you believe in reincarnation?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If science could clone you, would you want to be cloned?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If you were at a restaurant and they brought you the wrong dish, would you send it back?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If you found a wallet with $100 cash in it, would you try to return it?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If the guy at the store gave you $10 too much in change, would your return it?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Is racism alive and well in the United States?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If the world was always nighttime or daytime, which would you choose?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Nighttime",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Daytime",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Would you date a celebrity with all the public scrutiny and loss of privacy that comes with it?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If a man knocked on your door asking to use your phone, would you let him?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do smoke marijuana?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Frequently",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Occasionally",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Never",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If you saw your best friend’s partner kissing someone else, would you tell them?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you believe in God?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If a woman knocked on your door in the middle of the night asking for help, would you let her in?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you believe an eye for an eye?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If you saw some kids bullying another kid, would you step in?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If someone did or said something that offended you, would you tell them?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If you could have all the money and power in the world, but the catch is that you could never have a partner to share it with, would you take it?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If AI was so good that an android could be designed to fit your ideal of a perfect partner in every way, would you choose that over a human?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Would you rather get smarter or better looking?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Smarter",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Better Looking",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you believe in the death penalty?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If you found out that your partner was actually a criminal, would you report them?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you believe in the concept of a soul?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If you were really an android, would you want to know?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If there was a drug that maximized your brain to super-genius level but took a month off your life every time you took it, would you take it?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you believe that aliens exist?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If Jurassic Park was possible, do you think we should do it?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Can criminals be rehabilitated?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you believe alcohol is more dangerous than marijuana?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If your girlfriend and your mother changed bodies, and the only way to get them back to normal was to have sex with one of them, which do you choose?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Girlfriend in mom’s body",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Mom in girlfriend’s body",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If a biker cut you off in traffic, would you give him the finger?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Are conflicts in other countries our responsibility as well?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you believe the American judicial system works?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you believe in ghosts?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Would you rather be rich and a horrible person, or poor a good person?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Rich a-hole",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Poor saint",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you believe we’ll discover extraterrestrial life in our lifetime?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Are people inherently good or inherently evil?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Good",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Evil",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If you saw some big kids bullying on a smaller kid, would you step in?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If someone offered you the superpower of knowing what other people were thinking, would you take it?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you believe everyone is capable of evil?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If you were in a grocery store and saw someone stealing, would you tell anyone?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If a woman knocked on your door asking for help, would you let her in?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you believe marijuana should be legalized?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Can people change?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Would you rather be deaf or blind?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Deaf",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Blind",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Would you take a CEO job that paid millions a year knowing that the corporation itself was somewhat evil?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Are there smart people who fail at school?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you believe meat is murder?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If a woman cut you off in traffic, would you give her the finger?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do babies know right from wrong?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you believe in karma?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Is it better to have love and lost, or to have never loved at all?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Love and lost",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Never loved at all",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If you found a wallet with $1,000 cash in it, would you try to return it?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If you were at a restaurant and you didn’t like your order, would you ask for your money back?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If you were  in a situation where you were starving and stranded, could you eat another human being?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If you could travel 100 years into the future but never return to now, would you do it?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you believe there are undiscovered intelligent lifeforms living in the ocean?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you believe time travel is possible?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Is a high school diploma a requirement for success in life?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If someone is standing uncomfortably close to you in conversation, would you say something?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Other' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
