insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Would you or have you ever had a friend with benefits?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Hell Yeah",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Maybe",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Never",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever dated a boss or subordinate?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes.",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No but I would consider it.",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Never.",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "What if a man proposed with a down payment on a house instead of a ring?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"That’s awesome",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"That sucks",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Doesn’t matter",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you find that you are dating the same “type” over and over again?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes, déjà vu",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No, never",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever been cheated on?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes, several times",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes, once.",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Never",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever lied about your past to a partner?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"I have to",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"About little things",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"There’s nothing to lie about",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If you cheated on a partner, would you tell them?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you believe in the concept of The One?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Who should do the asking out—guys or girls?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Guys",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Girls",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you believe in soulmates?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you want to have kids?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Maybe",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you believe that if a relationship isn’t work out, divorce is an option?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Would you ever date someone a lot younger than you?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Is money important to a relationship?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you believe in astrology when it comes to compatibility?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes, it’s very interesting",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Don’t know enough",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Hell no.",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "What is more important to you, love or money?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Love",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Money",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "What kinds of gestures by a partner are important to you in a relationship?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Touch",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Sweet Talk",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Gifts",3);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Doing Nice Things",4);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Is it better to have a stable relationship or an exciting one?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Stable",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Exciting",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "How important is honesty in a relationship?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Very important",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Not important (Disconnected)",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"It’s impossible to be completely honest",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Would you consider dating a boss or subordinate?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes, why not.",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No way.",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Are you still friends with your ex(es)?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes, no problem.",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No way, when it’s over it’s over.",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Can exes be friends?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Is it worse to stay married in a bad relationship or get divorced?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Get divorced",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Stay married",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever had someone obsess over you?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes, it was awesome",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes, it was scary",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If you met someone with different political views would you consider dating them if they had other traits you appreciated?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Would you ever date a coworker?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes, why not.",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No way.",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If your partner cheated on you, would you want them to tell you?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Is someone’s past important to a relationship?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Past leads to the Present",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Depends on what’s there",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Only the Present matters",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Are you okay with dating someone who makes less money than you?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes, that’s awesome",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No, that sucks",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Don’t care",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you have trouble saying no to people?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Frequently",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Sometimes",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Never",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Is it possible to trust relationships after having been cheated on?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Would you ever date someone a lot older than you?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Are you okay with dating someone who makes more money than you?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes, that’s awesome",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No, that sucks",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Don’t care",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "How important is being able to trust your partner in a relationship?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Trust is everything",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Trust is earned",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Not so important",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Are there times when you have been jealous in a relationship?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"All the time",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes but I had a reason to",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Not really",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever been in a situation where you were friends with someone and it turned into more?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "How important is it that your partner gets along with your parents?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Very important",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Somewhat important",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Not really important",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "How important is it that you get along with your partner’s parents?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Very important",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Somewhat important",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Not really important",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Would you ever date someone if there was a large age difference?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Maybe",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Can sex on the first date lead to a real, meaningful relationship?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Definitely",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Possibly but it would be hard",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Probably not",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Would you be okay with a partner who has had one night stands in the past?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes, the past is the past",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Depends on the person",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No, it says something about their character",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If you were dating someone who had lots of friends of the same gender as you, would you have a problem with that?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes, that’s weird.",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Not a problem.",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Can friends become lovers?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes that’s the best way",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No, they are friends for a reason",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "What’s more important—physical attraction or mental compatibility?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Physical Attraction",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Mental Compatibility",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever had a one night stand?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes, it’s a lifestyle",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"A few",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Once",3);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Never",4);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you tell your partner(s) everything?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Definitely!",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Hell No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If you were dating someone who was friends with their ex(es), would you be okay with it?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Sure, no problem.",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No way.",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever dated a coworker?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes.",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No but I would consider it.",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Never.",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do men and women speak different languages?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Definitely",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Depends on personal chemistry",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No, they just need to learn how to communicate",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "How happy are you in your current relationship?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Very Happy",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Sorta Happy",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Not Happy",3);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Not Sure",4);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Is it possible to change your partner’s bad habits?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes, if addressed skillfully.",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No, people don’t change.",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "How important is self-confidence in a relationship?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Important",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Not important",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever dated someone you weren’t initially attracted to but then became attracted to?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If you met someone with different religious views would you consider dating them if they had other traits you appreciated?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "What do you think of on-again off-again relationships?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Don’t work",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Work in progress",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "What is your longest relationship?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"A few months",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"1-2 years",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"2+ years",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Would you date the ex of a friend?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Why Not",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Never",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever been obsessed with someone?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you cheated before?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes, several times",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes, once.",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Never",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Are you ready for a good relationship?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Definitely",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"I’m not sure",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If you knew then what you know now, would you choose to date your current partner?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes, definitely",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Hmmm…",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No, I would have done things differently.",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "What’s more important—financial security or love?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Financial Security",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Love",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you or would you date someone who had children from a previous relationship?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Sure",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Depends…",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Probably not.",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you believe in love at first sight?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes, definitely",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No, it’s not real",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Should women ask men out?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes!",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Depends on the woman",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No.",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Could you ever date a jealous partner?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes, it’s flattering",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes but they have to learn to trust",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If your partner had a problem with your friendship with your ex(es), what would you do?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"End the friendships.",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"End the relationship",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Nothing. They have to coexist.",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "What’s better—being friends with someone first then developing feelings, or dating?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Relationship' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Friends First",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Dating first",2);
