insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever had someone walk in on you while you were having sex?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Is sex better when you’re with someone you’ve been with for a while?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes, you know what each person likes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No, gets boring",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Would you be mad if you caught your partner masturbating?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever had a parent walk in on you while you were having sex?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever had an STD?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever had sex and then were too drunk to remember?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you think the use of sex accessories (toys, games, role play) spices up a relationship or is a substitute for intimacy?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Healthy spice",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"A crutch for lack of true intimacy",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you enjoy receiving oral sex?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever had sexual fantasies about a teacher?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "When you’re sleeping with someone new, is it hard for you to cum?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Only if I’m not into the person",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever slept with someone you are related to?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever slept with the significant other of a friend?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes but I felt terrible",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",3);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No but I want to",4);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever had sexual fantasies about a boss?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you prefer sex when you’re drunk or high?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever had anal sex?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes, love it.",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes, didn’t like it.",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you worry more about STDs or getting pregnant?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"STDs",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Pregnancy",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Both",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever had sex with a coworker?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Does it bother you to have sex while pets are watching?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever been blindfolded during sex?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever tied up your partner during sex?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever blindfolded a partner during sex?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you prefer your partner shaved, trimmed or natural “down there?”",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Shaved",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Trimmed",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Au Naturale",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever had a one night stand with a coworker?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you occasionally have one night stands to supplement your relationship?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Does it turn you on to know someone is watching you have sex?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever slept with someone you would be embarrassed about if your friends found out?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever had someone walk in on you while you were masturbating?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Is premarital sex a sin?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "What turns you on more, sex with a stranger or sex in a committed relationship?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Sex with a stranger",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Sex in a committed relationship",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you like to be tied up during sex?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever walked in on someone masturbating?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Would you have sex with someone significantly younger than you?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you watch porn?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Is being able to climax during sex a mental or physical thing?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Mental",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Physical",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you like it when you partner talks dirty to you during sex?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever slept with two members of the same family?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you enjoy giving oral sex?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever walked in on someone having sex?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever exchanged sex for gifts or favors?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Would you booty call an ex?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever used sex toys in bed?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever taken money for sex?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Never",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Once",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you have an open relationship that allows you to sleep with other people?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever had sex with someone whose name you didn’t know?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever had sexual fantasies about a friend?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Would you date someone whom you know has slept around in the past?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "How often do you have unprotected sex?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Never",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Sometimes",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"When I’m in a committed relationship",3);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Always",4);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever slept with someone while their partner was out of town?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "If you saw someone having sex (ie a neighbor) would you keep watching or look away?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Keep watching",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Look away",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Would you ever take money for sex?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Never",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Depends on how much",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever been tied up during sex?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Would you sleep with someone whom you know sleeps around?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Have you ever had a child walk in on you while you were having sex?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Would you have one night stands if no one ever found out?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you prefer circumcised or uncircumcised?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Circumcized",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Uncircumcized",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Would you have sex with someone significantly older than you?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Do you use vibrators when having sex with your partner?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Sometimes",2);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",3);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Does masturbating help or hurt a relationship?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Helps",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Hurts",2);
insert into question(user_id,content,question_category_id,question_status_id,question_type_id) select 1, "Would you sleep with someone you would be embarrassed about if your friends found out?",a.question_category_id,b.question_status_id,c.question_type_id from question_category a, question_status b, question_type c where a.name='Sex' and b.name='Approved' and c.name='Multiple Choice';
set @q_id = (select LAST_INSERT_ID() from question limit 1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"Yes",1);
insert into question_choice(question_id,content,choice_order) values(@q_id,"No",2);
