
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Time Woke Up');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='note',label='Notes:';

set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Time To Bed');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Slept');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Napped');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Studied');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Worked');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Read');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Pages Read');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Pages Wrote');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Weight');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Height');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Exercised');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Cardio');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Lifted Weights');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Distance Ran');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Distance Swam');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Distance Biked');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Distance Walked');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Practiced');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Number of Pushups');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Number of Pullups');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Number of Crunches');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Servings of Vegetables');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Servings of Fruit');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Servings of Meat');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Cups of Water');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Servings of Sweets');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Sodas Drank');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Alcoholic Beverages Drank');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Meals Ate');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Ate Breakfast');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Said I Love You');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Partner Said I Love You');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Parent Said I Love You');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Child Said I Love You');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Child Said I Hate You');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Showed Appreciation');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Partner Showed Appreciation');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Fight');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Argument');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Talked On Phone');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Date');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Sex');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Made Out');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Broke Up');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Mood');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Happiness');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Sadness');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Stress');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Anger');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Took Vitamins');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Took Meds');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Headache');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Stomachache');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Period Started');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Period Ended');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Doctor Appt');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Surgery');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Spent Time with Kids');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Spent Time with Partner');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Spent Time Alone');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Meditated');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Time Meditated');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Commute Time');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='TV Watched');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Web Surfing');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Cooked');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Cussed');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Cigarettes Smoked');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Watched Movie');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Concert');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Sporting Event');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Vacation');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Born');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Death');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Graduated');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Job Started');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Job Ended');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Engaged');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Married');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Divorced');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Moved');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Bought House');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Bought Car');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Award');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Lost Virginity');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Pregnant');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='QA_Asked');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='QA_Answered');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Note');
insert into event_definition set event_subcategory_id=@subcategory_id,parameter='note',label='Notes:';
