-- subcategory definitions
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Time Woke Up');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='time',label='Woke Up At';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Time To Bed');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='time',label='Went To Bed At';

set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Slept');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='minutes',label='Slept For';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Napped');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='minutes',label='Napped For';

set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Studied');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='minutes',label='Studied For';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Worked');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='minutes',label='Worked For';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Read');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='minutes',label='Read For';

set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Weight');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='weight',label='Weighed';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Height');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='height',label='My Height is';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Exercised');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='minutes',label='Exercised For';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Cardio');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='minutes',label='Did Cardio For';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Lifted Weights');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='minutes',label='Lifted Weights For';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Distance Ran');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='distance',label='Ran For';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Distance Swam');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='distance',label='Swam For';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Distance Biked');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='distance',label='Biked For';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Distance Walked');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='distance',label='Walked For';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Practiced');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='minutes',label='Practiced For';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Number of Pushups');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='quantity',label='Did How Many Pushups';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Number of Pullups');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='quantity',label='Did How Many Pullups';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Number of Crunches');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='quantity',label='Did How Many Crunches';

set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Servings of Vegetables');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='quantity',label='Ate How Many Servings of Vegetables';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Servings of Fruit');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='quantity',label='Ate How Many Servings Fruit';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Servings of Meat');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='quantity',label='Ate How Many Servings Meat';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Cups of Water');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='quantity',label='Drank How Many Cups of Water';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Servings of Sweets');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='quantity',label='Had How Many Servings of Sweets';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Sodas Drank');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='quantity',label='Drank How Many Sodas';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Alcoholic Beverages Drank');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='quantity',label='Had How Many Alcoholic Beverages';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Meals Ate');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='quantity',label='Had How Many Meals';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Ate Breakfast');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='boolean',label='Did You Eat Breakfast?';

set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Fight');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='with',label='Had a Fight With';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Talked On Phone');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='with',label='Talked on the Phone With';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Date');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='with',label='Had a Date With';
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='where',label='We Went To';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Sex');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='boolean',label='Did You Have Sex?';
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='with',label='With Whom?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Made Out');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='with',label='Made Out With';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Broke Up');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='with',label='Broke Up With';

set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Mood');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='scale_1_to_10',label='My Mood is';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Happiness');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='scale_1_to_10',label='My Level of Happiness is';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Sadness');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='scale_1_to_10',label='My Level of Sadness is';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Stress');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='scale_1_to_10',label='My Level of Stress is';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Anger');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='scale_1_to_10',label='My Level of Anger is';

set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Took Vitamins');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='boolean',label='Did You Take Vitamins?';
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='what',label='What Did you Take?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Took Meds');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='boolean',label='Did You Take Your Meds?';
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='what',label='What Did You Take?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Headache');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='scale_1_to_10',label='How Bad Do You Have a Headache?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Stomachache');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='scale_1_to_10',label='How Bad Does Your Stomache Hurt?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Period Started');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='boolean',label='Has Your Period Started?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Period Ended');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='boolean',label='Has Your Period Ended?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Doctor Appt');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='who',label='With Whom is it?';
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='what',label='What is it for?';
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='where',label='Where is the Appointment';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Surgery');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='what',label='What Are You Having Surgery for?';
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='where',label='Where is Your Surgery?';
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='time',label='What Time is Your Surgery?';

set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Spent Time with Kids');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='minutes',label='How Much Time Did You Spend With Kids?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Spent Time with Partner');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='minutes',label='How Much Time Did You Spend With Your Partner?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Spent Time Alone');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='minutes',label='How Much Time Did You Spend Alone';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Meditated');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='boolean',label='Did You Meditate?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Time Meditated');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='minutes',label='How Long Did You Meditate?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Commute Time');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='minutes',label='What Was Your Commute Time?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='TV Watched');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='minutes',label='How Long Did You Watch TV?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Web Surfing');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='minutes',label='How Long Did You Surf the Web?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Cussed');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='boolean',label='Did You Cuss?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Watched Movie');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='title',label='What Movie Did You Watch?';
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='with',label='With Whom Did You Watch it?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Concert');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='who',label='Who Did You See in Concert?';
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='with',label='With Whom Did You Go?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Sporting Event');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='who',label='What Sporting Event Did You Attend?';
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='with',label='With Whom Did You Go?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Vacation');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='who',label='Where Did You Go?';
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='with',label='Who Did You Go With?';
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='start_date',label='When Did You Leave?';
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='end_date',label='When Did You Come Back?';

set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Born');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='where',label='Where Were You Born?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Death');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='who',label='Who Died?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Graduated');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='from',label='Where Did You Graduate From?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Job Started');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='company',label='What Company?';
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='title',label='What Was Your Job Title?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Job Ended');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='company',label='What Company?';
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='title',label='What Was Your Job Title?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Engaged');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='to',label='To Who?';
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='where',label='Where?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Married');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='to',label='To Who?';
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='where',label='Where Were You Married?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Divorced');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='from',label='From Who?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Moved');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='address',label='Where Did You Move?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Bought House');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='address',label='Where?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Bought Car');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='what',label='What Kind of Car?';
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='how_much',label='How Much Did it Cost?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Award');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='title',label='What Award?';
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='by',label='By Who?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Lost Virginity');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='with',label='With Whom?';
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='where',label='Where?';
set @subcategory_id = (select event_subcategory_id from event_subcategory where name='Pregnant');
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='due',label='When is Your Due Date?';
insert into event_definition set event_subcategory_id=@subcategory_id, parameter='born',label='When Did You Have the Baby?';

